### PR TITLE
text: do not nuke all textstrings on level load

### LINKED ISSUE #164: Fix console text disappearing too early
Currently, all text strings are nuked with a call to `Text_Init` during level initialization. This causes problems for #162, where the messages for `/endlevel` and similar commands get immediately lost.

### PR DESCRIPTION
**Pull request by rr-**
Resolves #164, eg issuing `/play` and the like should no longer clear the console logs.

The objective is to ensure that on-screen text gets removed when it should. For example the inventory arrows shouldn't stay when the player executes commands such as `/play`, or the ammo counter should disappear when the player ends the level. I've tested several cases, but I believe I might've missed some.

### CODE REVIEW

**Review by lahm86 — COMMENTED** [review]
The only issue I've noticed is that the title screen no longer has the TR2X version string.

**Comment by aredfan** [comment]
The end level stats and the inventory arrows disappear as expected when using cheats.  The ammo counter is cleared between levels.

There's an issue with the ammo counter getting carried over to another level, if cheats is used:

- If you execute `/play` or `/load` during demo mode, and the ammo count is visible.
- If you execute` /play`, `/load` or `/demo` in-game e.g. Floating Islands, and the ammo count is visible.

**Comment by rr-** [comment]
@aredfan @lahm86 fixed.

**Review by lahm86 — APPROVED** [review]

**Review by aredfan — APPROVED** [review]
I've checked the ammo counter and re-tested all prior issues. Everything looks great and polished.

**Pull request merged**
