### PR TITLE
Console goodies

### PR DESCRIPTION
**Pull request by rr-**
Adds new commands:

- `/endlevel`
- `/demo`
- `/title`
- `/play [level]`
- `/exit`
- `/fly`

Test build: https://home.wind.garden/serve/pub/TR2X-0.2-318-g6cce4b1-Windows.zip

Known issues (checked means it's resolved):

- [x] Running `/title` while in the title screen exits the game instead.
- [x] Selecting Lara's Home in the title screen and issuing `/demo` will result in weird inventory ring camera angles.
- [x] Loading a level won't display a message in the console because the game logic currently clears all text strings on level load.
- [x] We still face the problem of not debouncing the user input. This manifests in a number of ways, e.g. if the player does not lift their finger from the key:
    -  …after issuing the `/demo` command, the demo will start and then immediately exit, assuming the user has aborted it with a new input.
    - …after issuing the `/endlevel` command, the game will not bring up the end of level stats.
    - …after pressing escape to close the console, the game will immediately open the inventory.
- [x] Selecting Lara's Home on the main menu starts The Great Wall.
- [x] Loading a savegame on the main menu starts The Great Wall.
- [x] Executing play 0 on the main menu closes the game.
- [x] Using fly when in the boat/skidoo can cause issues but that's probably to be expected.
- [x] Executing the `/exit` command in the end of level stats doesn't immediately work
- [ ] Opening the console conflicts with flares
    - [x] This breaks the first demo, where Lara doesn't take out a flare
- [x] The level stats work every other time
- [x] Pressing 0-9 trigger item use if the console is open

### CODE REVIEW

**Comment by walkawayy** [comment]
> Known issues I'd appreciate help with:
> 
> * Running `/title` while in the title screen exits the game instead.

So this is happening because in `TitleSequence`, `Inv_Display` returns `GFD_EXIT_TO_TITLE` due to the override if block in there:

```
        if (g_GF_OverrideDir != (GAME_FLOW_DIR)-1) {
            const GAME_FLOW_DIR dir = g_GF_OverrideDir;
            g_GF_OverrideDir = (GAME_FLOW_DIR)-1;
            g_Inv_IsActive = 0;
            g_Inv_ExtraData[0] = 0;
            return dir;
        }
```

Then, ` TitleSequence` falls through all the way to the end which is `return GFD_EXIT_GAME;`. To fix it, I think the easiest way would be to check if we are on the title screen, and if so, do not execute the console title command. Otherwise, we would need to check if we are on the title screen in `Inv_Display`'s override check. Worst option would be handling it in `TitleSequence` after returning from `Inv_Display` because all of those cases are returning a gameflow direction for a demo, saved game, new game, etc.

> * Selecting Lara's Home in the title screen and issuing `/demo` will result in weird inventory ring camera angles.

My guess is the override returns early from `Inv_Display`, so the ring is never cleaned up properly? It looks like on `RNG_DESELECT`, `Inv_Ring_MotionSetup` and `Inv_Ring_MotionRotation` run. Also `S_FinishInventory` later on. My guess is one of these calls would cleanup the `RNG_SELECTED`'s angle change.

> * Loading a level won't display a message in the console because the game logic currently clears all text strings on level load.

Weird thing is when I try `play 0` from a normal game level, the console shows `Loading Lara's Home`. But, nothing happens. For any other level, I don't see any console text, but the game loads the level properly.

> * We still face the problem of not debouncing the user input. For instance, if the player does not lift their finger from the key after issuing the `/demo` command, the demo will start and then immediately exit, assuming the user has aborted it with a new input.

This seems like a future issue / PR?


Lastly, there seems to be another bug where selecting exit game from the passport in the title screen actually starts a new game and loads The Great Wall level.

**Comment by aredfan** [comment]
I've come across these issues while testing the build.

- Selecting Lara's Home on the main menu starts The Great Wall.
- Loading a savegame on the main menu starts The Great Wall.
- Executing `play 0` on the main menu closes the game.
- Executing `endlevel` in Venice (level 2) doesn't bring up the end of level stats.
- Executing `endlevel` in Bartoli's Hideout (level 3) shows 'Venice' on the end of level stats. **Edit:** To reproduce, load Venice first, then skip level to Bartoli's Hideout.
- Using `fly` when in the boat/skidoo can cause issues but that's probably to be expected.

**Comment by rr-** [comment]
- Executing endlevel in Venice (level 2) doesn't bring up the end of level stats.
- Executing endlevel in Bartoli's Hideout (level 3) shows 'Venice' on the end of level stats. Edit: To reproduce, load Venice first, then skip level to Bartoli's Hideout.

I think the mismatched level dialogs got fixed with the most recent fix. As for the game forgoing to bring up the stats dialog – this is the same as `/demo` often not playing, e.g. the inputs register too fast and immediately close the stats dialog.

**Comment by rr-** [comment]
New build: https://home.wind.garden/serve/pub/TR2X-0.2-322-g7641bb0-Windows.zip

The clearing of console logs on level load will have to be tackled in a separate issue as it requires more decomp work.

**Comment by aredfan** [comment]
The input debouncing fix is working beautifully on the main menu. There's a new issue with Lara not taking out a flare at the start of Demo 1 whether you wait for the demo to start, or by executing `/demo`.

It might be an issue that `/demo` can be executed from within the game or the inventory.

The `/exit` command works well on the main menu, inventory and gameplay. There's a slight hold-up when executing `/exit` in the end of level stats, but the game closes after pressing action.

I think I still have the input debouncing in-game because the Venice stats gets skipped.

**Edit:** It might not be input debouncing.  Try these steps:

1. `/play 2`
2. `/endlevel`
3. `/play 2`
4. `/endlevel`
5. `/play 2`
6. `/endlevel`

I noticed the level stats appear every second attempt.

**Comment by walkawayy** [comment]
I wonder if the flare issue might be related to the console and conflicting input keys? The default input to draw a flare is / which is also how the console opens. I noticed that during normal gameplay she sometimes will take out a flare for the hotkey, but normally the console just opens instead.

**Comment by aredfan** [comment]
> I wonder if the flare issue might be related to the console and conflicting input keys? The default input to draw a flare is / which is also how the console opens. I noticed that during normal gameplay she sometimes will take out a flare for the hotkey, but normally the console just opens instead.

I had similar experience with Lara taking out a flare if dev console is open and the last number I type is 0 before hitting enter too quickly.

Btw the issue in #75 have resurfaced. There is 0-9 conflict when the dev console is open.

**Comment by rr-** [comment]
New test build: https://home.wind.garden/serve/pub/TR2X-0.2-323-g75f3040-Windows.zip

Remaining issues to be tackled separately as they require porting more code:

- flare / console key conflicts – #163 (Lara not taking out the flare in the demo _was_ fixed though)
- text disappearing on level load – #164

The remaining issues should've been fixed.

**Comment by aredfan** [comment]
0-9 is no longer conflicting when dev console is open. End of level stats appear when skipping every level and `/exit` during stats quits the game instantly. LGTM. 

The input debouncing is back when I execute the demo, but I was able to get the demo to start by tapping enter as briefly as possible. Lara takes out a flare when waiting for or executing demo 1.

**Review by aredfan — APPROVED** [review]

**Comment by rr-** [comment]
Fixed the regression around demo input debouncing: https://home.wind.garden/serve/pub/TR2X-0.2-323-g3c7118d-Windows.zip

**Comment by aredfan** [comment]
> Fixed the regression around demo input debouncing: https://home.wind.garden/serve/pub/TR2X-0.2-323-g3c7118d-Windows.zip

It's easier for me to execute the demo now. Thank you for fixing it. 👍

**Comment by rr-** [comment]
Included a fix from Lahm to make the fly command faster like in TR1X, and to fix its behavior during when issuing during the Offshore Rig initial animation:

https://home.wind.garden/serve/pub/TR2X-0.2-323-gcf0dc53-Windows.zip

**Comment by aredfan** [comment]
I found one small issue. When Lara is on fire, activating the fly cheat doesn't put out the fire.

This can be tested in the first level, room 65.

**Review by walkawayy — APPROVED** [review]
I didn't notice any issues other than the fire issue reported.

**Comment by rr-** [comment]
> I found one small issue. When Lara is on fire, activating the fly cheat doesn't put out the fire.
> 
> This can be tested in the first level, room 65.

Thanks. I can't act on this just yet as we don't have the fire routines decompiled. I have a TODO left in the comment. Let's track it as an issue. I'll wait for Lahm's approval and then merge the PR.

**Review by lahm86 — APPROVED** [review]

**Comment by lahm86** [comment]
I've just realised inventory buffering is no longer possible - it was in the build I tried yesterday, I think it was before the input fixes. Best handled in a separate issue?

**Comment by rr-** [comment]
> I've just realised inventory buffering is no longer possible - it was in the build I tried yesterday, I think it was before the input fixes. Best handled in a separate issue?

I'd rather not introduce regressions into develop anymore unless absolutely necessary. I'll check.

**Comment by rr-** [comment]
@lahm86 I've fixed the inventory buffering.

**Pull request merged**
