### PR TITLE
Add UI framework

### PR DESCRIPTION
**Pull request by rr-**
This build replaces the old spaghetti-based controls dialog with a new widget-based UI. It should behave identically in reaction to player inputs, navigation etc. The visual margins and sizes may be slightly different, but that's okay, since we're overhauling this dialog anyway.

This build https://github.com/LostArtefacts/TR2X/actions/runs/10746338445 renders both dialogs at the same time to demonstrate behavior parity.

I haven't tested this with lower resolutions.

### CODE REVIEW

**Comment by aredfan** [comment]
The new controls UI look good to me when trying out a few resolutions between 640x480 and 1440x1080.

I did notice an issue with some of the text overlapping the box margins from above. Left is OG, right is TR2X.

**Review by lahm86 — APPROVED** [review]
Very nice solution 😌

**Comment by rr-** [comment]
@aredfan fixed.
@lahm86 changed the widget storage to use `UI_WIDGET *UI_MyWidget_Create()` idiom rather than `UI_WIDGET my_widget; UI_MyWidget_Init(&my_widget);`. This means slightly more allocations (we can no longer allocate arrays of widgets in a single go), but I found the code easier to read.

**Review by aredfan — APPROVED** [review]
LGTM and thank you. 👍

**Comment by rr-** [comment]
Thank you. I'll clean up the commits a bit and then merge.

**Pull request merged**
