### PR TITLE
More console commands

### PR DESCRIPTION
**Pull request by rr-**
- Adds an easter egg command.
- Adds `/save` and `/load`.
- Adds `/flip`.
- Adds the door cheat to the fly mode.
- And finally, adds the ability for `/tp` to teleport to specific items.

The last bullet is the source of the biggest changes. To achieve that, we need to know the object names, requiring actual strings instead of numeric enum values. Thus, in order to avoid hardcoding things, we're introducing the gameflow JSON file. Currently, it's very minimal. It only contains TR2X-specific strings and object names, but it already allows renaming objects per level. For example, in snowy levels, the tiger is called `Snow Leopard`, so we can use `/tp leo` instead of `/tp tiger`.

Game strings (which got backported from TR1X) still work when removed from the gameflow file as they embed fallback strings in the .exe. The same holds true for object names.

Object aliases is something that is not currently supported.

### CODE REVIEW

**Review by walkawayy — APPROVED** [review]
LGTM. Is the libtrx commit meant to be here?

**Comment by aredfan** [comment]
I'm glad to see we can teleport to items now, it'll make collecting secrets much faster!

Not sure if it's an issue but I noticed it's possible to /save in Lara's Home.

**Comment by rr-** [comment]
> LGTM. Is the libtrx commit meant to be here?

Yes – we're using new enum macros.

**Review by aredfan — APPROVED** [review]

**Comment by aredfan** [comment]
The delay when teleporting in the start of Offshore Rig and the end of Home Sweet Home is fixed. Thank you.

The /save command is prevented during cutscenes and demo modes.  It does still work in Lara's Home.

Overall, LGTM.

**Pull request merged**
