### PR TITLE
Port sound samples to SDL

### PR DESCRIPTION
**Pull request by rr-**
Test build:
https://nebula.wind.garden/serve/pub/TR2X-0.1.1-35-gc42dbb8-Windows.zip

### CODE REVIEW

**Comment by lahm86** [comment]
There are no sounds underwater at all, I can't seem to get them to trigger in any way.

There also seems to be a problem with sounds cutting out altogether, and at times the volume going extremely high. I'm struggling to pinpoint the cause, but I am wondering if it's related to room sound sources i.e. the (above) water loop SFX you hear in TR2. It's just a hunch to be honest, as they seem to cut out when you'd expect these sounds to kick in, such as when emerging from the guardhouse in GW. There is a sound source for ID 59 at the waypoint here.

image

Here is a demo. I'm not sure if my sound source theory is correct for the first issue in the video, afaik the helicopter just triggers `Sound_Effect` like any other call to it. Maybe it's related to the distance from Lara?

https://youtu.be/X08LAVyfqM0 (warning: very high volume at 00:28 for a few seconds)

[TR2X.log](https://github.com/LostArtefacts/TR2X/files/15218457/TR2X.log)

**Comment by rr-** [comment]
@lahm86 thanks for the tests. Can you confirm if these issues are also present the latest develop snapshot that has Sound_Effect and the bunch already decompiled, but not yet bulldozed to use SDL? Just to rule out a regression in the decompilation process.

**Comment by lahm86** [comment]
> @lahm86 thanks for the tests. Can you confirm if these issues are also present the latest develop snapshot that has Sound_Effect and the bunch already decompiled, but not yet bulldozed to use SDL? Just to rule out a regression in the decompilation process.

Everything sounds good in the latest develop snapshot 👍

**Comment by rr-** [comment]
@lahm86 it should be now fixed, thankfully it was a dumb mistake of not converting the ingame sound-related units to libtrx units in one place for looped samples.

**Review by lahm86 — APPROVED** [review]
All sounds good to me 👍

**Review by walkawayy — APPROVED** [review]

**Pull request merged**
